sudo: false
language: python
python: 2.7
install:
  - pip install codecov
script:
  - coverage run tests.py
after_success:
  - echo "${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}"
  - echo "$TRAVIS_JOB_NUMBER"
  - echo "$TRAVIS_PULL_REQUEST"
  - echo "$TRAVIS_JOB_ID"
  - echo "$TRAVIS_REPO_SLUG"
  - echo "$env,TRAVIS_OS_NAME"
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"
  - echo this is a patch 2
  - bash <(curl -s https://codecov.io/bash) -t 646448aa-c2cb-43f5-8214-da5d0ef8118f
